# Generated by Django 2.0.2 on 2018-02-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('main_page', 'main page'), ('schedule_list', 'schedule page'), ('services_list', 'services page'), ('news_list', 'news list page'), ('news_detail', 'news detail page'), ('document_list', 'documents page'), ('contact_list', 'contacts page'), ('faq_list', 'faq page'), ('job_list', 'job page')], default='main_page', max_length=50, unique=True, verbose_name='page')),
                ('additional_header', models.TextField(blank=True, verbose_name='additional header')),
                ('additional_footer', models.TextField(blank=True, verbose_name='additional footer')),
                ('slider_proxy', models.TextField(blank=True, verbose_name='slider proxy')),
                ('enabled', models.BooleanField(default=True, help_text='show/hide record.', verbose_name='enabled')),
            ],
            options={
                'ordering': ['page'],
                'verbose_name': 'page content',
                'verbose_name_plural': 'pages content',
            },
        ),
    ]
