# Generated by Django 2.0.2 on 2018-02-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='user fio')),
                ('contact', models.CharField(max_length=255, verbose_name='user contact')),
                ('content', models.TextField(verbose_name='question content')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('answered', models.BooleanField(default=False, verbose_name='answered')),
            ],
            options={
                'ordering': ['-create_date'],
                'verbose_name': 'question item',
                'verbose_name_plural': 'questions items',
            },
        ),
    ]
