# Generated by Django 2.0.2 on 2018-02-17 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='agent title')),
                ('url', models.URLField(verbose_name='agent url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schedule', verbose_name='agent logo')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'agent item',
                'verbose_name_plural': 'agents items',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='show/hide record.', verbose_name='enabled')),
                ('pub_date_start', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Rocord will be visible form this date.', verbose_name='start date for publication')),
                ('pub_date_end', models.DateTimeField(blank=True, db_index=True, help_text='Rocord will be invisible form this date.', null=True, verbose_name='end date for publication')),
                ('weight', models.PositiveIntegerField(db_index=True, default=0, help_text='Rocord will be first with greate weight.', verbose_name='weight of publication')),
                ('direction', models.CharField(max_length=255, verbose_name='flight direction')),
                ('flight_no', models.CharField(blank=True, max_length=255, verbose_name='flight number')),
                ('departure', models.TextField(verbose_name='flight departure')),
                ('arrival', models.TextField(verbose_name='flight arrival')),
                ('order', models.TextField(blank=True, verbose_name='flight order')),
                ('agents', models.ManyToManyField(blank=True, to='schedule.Agent', verbose_name='flight agents')),
            ],
            options={
                'ordering': ['-weight', 'direction'],
                'verbose_name': 'flight item',
                'verbose_name_plural': 'flights items',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='show/hide record.', verbose_name='enabled')),
                ('pub_date_start', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Rocord will be visible form this date.', verbose_name='start date for publication')),
                ('pub_date_end', models.DateTimeField(blank=True, db_index=True, help_text='Rocord will be invisible form this date.', null=True, verbose_name='end date for publication')),
                ('weight', models.PositiveIntegerField(db_index=True, default=0, help_text='Rocord will be first with greate weight.', verbose_name='weight of publication')),
                ('content', models.TextField(verbose_name='note content')),
            ],
            options={
                'ordering': ['-weight', 'content'],
                'verbose_name': 'note item',
                'verbose_name_plural': 'notes items',
            },
        ),
        migrations.CreateModel(
            name='PaymentBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='show/hide record.', verbose_name='enabled')),
                ('pub_date_start', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Rocord will be visible form this date.', verbose_name='start date for publication')),
                ('pub_date_end', models.DateTimeField(blank=True, db_index=True, help_text='Rocord will be invisible form this date.', null=True, verbose_name='end date for publication')),
                ('weight', models.PositiveIntegerField(db_index=True, default=0, help_text='Rocord will be first with greate weight.', verbose_name='weight of publication')),
                ('image', models.ImageField(upload_to='schedule', verbose_name='payment image')),
                ('title', models.CharField(max_length=255, verbose_name='payment title')),
            ],
            options={
                'ordering': ['-weight', 'title'],
                'verbose_name': 'payment banner item',
                'verbose_name_plural': 'payment banners items',
            },
        ),
    ]
