# Generated by Django 2.0.2 on 2018-02-17 16:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='show/hide record.', verbose_name='enabled')),
                ('pub_date_start', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Rocord will be visible form this date.', verbose_name='start date for publication')),
                ('pub_date_end', models.DateTimeField(blank=True, db_index=True, help_text='Rocord will be invisible form this date.', null=True, verbose_name='end date for publication')),
                ('weight', models.PositiveIntegerField(db_index=True, default=0, help_text='Rocord will be first with greate weight.', verbose_name='weight of publication')),
                ('content', models.TextField(verbose_name='note content')),
            ],
            options={
                'ordering': ['-weight', 'content'],
                'verbose_name': 'note item',
                'verbose_name_plural': 'notes items',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='show/hide record.', verbose_name='enabled')),
                ('pub_date_start', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Rocord will be visible form this date.', verbose_name='start date for publication')),
                ('pub_date_end', models.DateTimeField(blank=True, db_index=True, help_text='Rocord will be invisible form this date.', null=True, verbose_name='end date for publication')),
                ('weight', models.PositiveIntegerField(db_index=True, default=0, help_text='Rocord will be first with greate weight.', verbose_name='weight of publication')),
                ('title', models.CharField(max_length=255, verbose_name='vacancy title')),
                ('description', models.TextField(blank=True, verbose_name='vacancy description')),
                ('requirements', models.TextField(blank=True, verbose_name='vacancy requirements')),
                ('schedule', models.CharField(blank=True, max_length=255, verbose_name='vacancy schedule')),
                ('payment', models.CharField(blank=True, max_length=255, verbose_name='vacancy payment')),
                ('contacts', models.CharField(blank=True, max_length=255, verbose_name='vacancy contacts')),
                ('additionally', models.TextField(blank=True, verbose_name='vacancy additionally')),
            ],
            options={
                'ordering': ['-weight', '-pub_date_start'],
                'verbose_name': 'vacancy',
                'verbose_name_plural': 'vacances',
            },
        ),
        migrations.CreateModel(
            name='VacancyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='response fio')),
                ('phone', models.CharField(max_length=255, verbose_name='response phone')),
                ('about_self', models.TextField(blank=True, verbose_name='vacancy description')),
                ('summary', models.FileField(blank=True, upload_to='job', verbose_name='response summary')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='response date')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Vacancy', verbose_name='vacancy')),
            ],
            options={
                'ordering': ['-create_date'],
                'verbose_name': 'vacancy response',
                'verbose_name_plural': 'vacances responses',
            },
        ),
    ]
