# Generated by Django 2.0.2 on 2018-02-17 16:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='show/hide record.', verbose_name='enabled')),
                ('pub_date_start', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Rocord will be visible form this date.', verbose_name='start date for publication')),
                ('pub_date_end', models.DateTimeField(blank=True, db_index=True, help_text='Rocord will be invisible form this date.', null=True, verbose_name='end date for publication')),
                ('weight', models.PositiveIntegerField(db_index=True, default=0, help_text='Rocord will be first with greate weight.', verbose_name='weight of publication')),
                ('name', models.CharField(max_length=255, verbose_name='block name')),
                ('content_rich', models.TextField(blank=True, verbose_name='rich content')),
                ('content_plane', models.TextField(blank=True, verbose_name='plane content')),
            ],
            options={
                'ordering': ['-weight', '-pub_date_start'],
                'verbose_name': 'content block item',
                'verbose_name_plural': 'content block items',
            },
        ),
        migrations.CreateModel(
            name='SideContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='show/hide record.', verbose_name='enabled')),
                ('pub_date_start', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Rocord will be visible form this date.', verbose_name='start date for publication')),
                ('pub_date_end', models.DateTimeField(blank=True, db_index=True, help_text='Rocord will be invisible form this date.', null=True, verbose_name='end date for publication')),
                ('weight', models.PositiveIntegerField(db_index=True, default=0, help_text='Rocord will be first with greate weight.', verbose_name='weight of publication')),
                ('name', models.CharField(max_length=255, verbose_name='content name')),
                ('content_rich', models.TextField(blank=True, verbose_name='rich content')),
                ('content_plane', models.TextField(blank=True, verbose_name='plane content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='history', verbose_name='image content')),
                ('side', models.CharField(choices=[('LF', 'left'), ('RG', 'right')], max_length=255, verbose_name='content side')),
                ('detail_content_rich', models.TextField(blank=True, verbose_name='detail rich content')),
                ('detail_content_plane', models.TextField(blank=True, verbose_name='detail plane content')),
                ('detail_img_adjustment', models.CharField(blank=True, choices=[('WD', 'by width'), ('HG', 'by height')], max_length=255, verbose_name='detail image adjustment')),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.ContentBlock', verbose_name='content block item')),
            ],
            options={
                'ordering': ['content_block', 'side', '-weight', '-pub_date_start'],
                'verbose_name': 'side content item',
                'verbose_name_plural': 'side content items',
            },
        ),
    ]
