# Generated by Django 2.0.2 on 2018-02-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='text on slide', verbose_name='slide title')),
                ('image', models.ImageField(help_text='image of slide', upload_to='slider', verbose_name='slide image')),
                ('weight', models.IntegerField(default=0, help_text='determine the order of slides', verbose_name='weight')),
                ('enabled', models.BooleanField(default=True, help_text='if set, then slide will show', verbose_name='enabled')),
            ],
            options={
                'verbose_name': 'slide',
                'verbose_name_plural': 'slides',
                'ordering': ['-weight'],
            },
        ),
    ]
